### PR TITLE
Carousel

### PR DESCRIPTION
**Pull request by Dash293**
merging carousel branch to dev branch

### CODE REVIEW

**Review by LuigiMenez — CHANGES_REQUESTED** [review]
Not accepted a dead code line 2 and 3 CarrousselNews/index.jsx

**Review by LuigiMenez — APPROVED** [review]
Good

**Review by LuigiMenez — CHANGES_REQUESTED** [review]
Is not review from SM

**Review by LoicBrassart — APPROVED** [review]
SnE

**Review by LuigiMenez — APPROVED** [review]
Ok

**Review by Elfaram — APPROVED** [review]

**Pull request merged**
